### ISSUE TITLE
Broken 

### ISSUE THREAD

**Issue by Intel-i80486-DX4** [PlutoSolutions/Snow#3]
Full Log: https://paste.ee/p/Qs7q8

When starting client

[21:18:15] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:15] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:15] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:15] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:15] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:15] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:15] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:15] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:15] [Client thread/INFO] [FML]: Injecting itemstacks
[21:18:15] [Client thread/INFO] [FML]: Itemstack injection complete
[21:18:15] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[21:18:15] [Client thread/INFO] [Snow]: 

Initializing Snow 4.3
[21:18:16] [Thread-4/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[21:18:16] [Thread-4/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[21:18:16] [Thread-4/INFO] [net.minecraft.client.audio.SoundManager]: OpenAL initialized.
[21:18:16] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Sound engine started
[21:18:18] [Client thread/INFO] [Snow]: Modules initialized
[21:18:18] [Client thread/INFO] [Snow]: Commands initialized
[21:18:18] [Client thread/ERROR] [FML]: Unable to determine registrant mod for me.snowmii.snow.client.2K@2d1e49b3. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:75) [EventBus.class:?]
	at me.snowmii.snow.client.0.c(Unknown Source) [0.class:?]
	at me.snowmii.snow.client.c.qf(Unknown Source) [c.class:?]
	at net.minecraft.client.Minecraft.handler$onStartUp$zbh000(Minecraft.java) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[21:18:18] [Client thread/WARN] [mixin]: Method overwrite conflict for setIsHittingBlock in mixins.baritone.json:MixinPlayerControllerMP, previously written by me.snowmii.snow.client.mixin.mixins.accessors.player.AccessorPlayerControllerMP. Skipping method.
[21:18:19] [Client thread/INFO] [Snow]: Configurations loaded
[21:18:21] [Client thread/INFO] [Snow]: Friends loaded
[21:18:21] [Client thread/INFO] [Snow]: Snow initialized successfully.
[21:18:22] [Client thread/INFO] [FML]: Max texture size: 16384
[21:18:23] [Client thread/INFO] [net.minecraft.client.renderer.texture.TextureMap]: Created: 512x512 textures-atlas
[21:18:24] [Client thread/INFO] [FML]: Applying holder lookups
[21:18:24] [Client thread/INFO] [FML]: Holder lookups applied
[21:18:24] [Client thread/INFO] [FML]: Injecting itemstacks
[21:18:24] [Client thread/INFO] [FML]: Itemstack injection complete
[21:18:24] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[21:18:25] [Client thread/INFO] [STDOUT]: [baritone.api.utils.SettingsUtil:readAndApply:-1]: Baritone settings file not found, resetting.
[21:20:22] [Client thread/WARN] [net.minecraft.client.gui.GuiMultiplayer]: Unable to start LAN server detection: Can't assign requested address
[21:20:24] [Client thread/WARN] [net.minecraft.client.gui.GuiMultiplayer]: Unable to start LAN server detection: Can't assign requested address
[21:20:27] [Netty Client IO #1/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER
[21:20:27] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER

when attempting to open GUI

[21:20:42] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1151) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.GL30.glGenVertexArrays(GL30.java:1550) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at me.snowmii.snow.client.hO.8h(Unknown Source) ~[hO.class:?]
	at me.snowmii.snow.client.hR.c(Unknown Source) ~[hR.class:?]
	at me.snowmii.snow.client.hK.qz(Unknown Source) ~[hK.class:?]
	at me.snowmii.snow.client.i9.c(Unknown Source) ~[i9.class:?]
	at me.snowmii.snow.client.i6.iH(Unknown Source) ~[i6.class:?]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_74]
	at me.snowmii.snow.client.i9.c(Unknown Source) ~[i9.class:?]
	at me.snowmii.snow.client.i6.zX(Unknown Source) ~[i6.class:?]
	at me.snowmii.snow.client.io.2U(Unknown Source) ~[io.class:?]
	at me.snowmii.snow.client.iq.zX(Unknown Source) ~[iq.class:?]
	at me.snowmii.snow.client.io.2U(Unknown Source) ~[io.class:?]
	at me.snowmii.snow.client.1Y.a2(Unknown Source) ~[1Y.class:?]
	at me.snowmii.snow.client.1A.c(Unknown Source) ~[1A.class:?]
	at me.snowmii.snow.client.1z.func_73863_a(Unknown Source) ~[1z.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) ~[buq.class:?]
	... 17 more

**Comment by mr-nv** [comment]
works on my machine

**Comment by Intel-i80486-DX4** [comment]
*well not on mine, obviously.* why the hell am i having to troubleshoot? (What version of forge are you using?)

**Comment by mr-nv** [comment]
![image](https://user-images.githubusercontent.com/31269663/158481999-e13e0e71-b845-4b5b-ae84-8dc979611017.png)
14.23.5.2859

**Comment by mr-nv** [comment]
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.GL30.glGenVertexArrays(GL30.java:1550) ~[lwjgl-2.9.4-nightly-20150209.jar:?]

googling that tells me that theres something with your video card or your video card drivers

**Comment by Intel-i80486-DX4** [comment]
i wonder if this needs optifine like moneymod. (worth a try.)

**Comment by mr-nv** [comment]
nah i dont have optifine installed and it works

**Comment by Intel-i80486-DX4** [comment]
well idek where to begin with this, using the command prefix (*) doesn't even show a "command not found" thing, just blanks. did try *help and *bind, still nothing. i suspect foul play with forge's event system.

**Comment by mr-nv** [comment]
commands in snow dont print in chat, instead they appear (if you havent configured anything) at the top left corner
try opening the gui, the bind is ENTER for whatever reason

**Comment by Intel-i80486-DX4** [comment]
crashes as described, with the java.lang.IllegalStateException.

**Comment by Intel-i80486-DX4** [comment]
what launcher and jvm are you using?

**Comment by mr-nv** [comment]
multimc and jdk1.8.0_241
i see that you have a mac so im almost certain that the problem comes from that
you should try searching for fixes on google or somewhere

**Comment by Intel-i80486-DX4** [comment]
out of curiousity, do you get the same error on client init? ([FML]: Unable to determine registrant mod for me.snowmii.snow.client.2K@702bb00f. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:75) [EventBus.class:?]
	at me.snowmii.snow.client.0.c(Unknown Source) [0.class:?]
	at me.snowmii.snow.client.c.qf(Unknown Source) [c.class:?]
	at net.minecraft.client.Minecraft.handler$onStartUp$zbh000(Minecraft.java) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:504) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?])

**Comment by Intel-i80486-DX4** [comment]
oh and, were you using any other mods other then snow? (had to ask.)

**Comment by mr-nv** [comment]
just ignore that error
no, only snow

**Comment by Intel-i80486-DX4** [comment]
well i'm stumped, prolly something to do with graphics drivers. as you said.

**Comment by Intel-i80486-DX4** [comment]
well that or lwjgl is being fucky
